# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00b4e39dfcade8ba9892da82c4b3ad5ccd60fe2a1ef738b3e47b0607d12fdf063b82ac7661e45cfa01d67adfb72288d98109fe450ea3a8839f57f2966c20aeda

test:
  secret_key_base: 710558c72faf1c3ba2c0c387b8e2daeac873947c005aca7ec2cacd9d4e66b837785331baa72d2752c75168773c53904359265a7102ea1feda0674d5859daaeea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
